spring:
  application:
    name: springGraphql

server:
  http2:
    enabled: true

graphql:
  servlet:
    max-query-depth: 100
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
        - name: Bank account sample query
          query: classpath:playground/bank_account.graphql
          variables: classpath:playground/bank_account_variables.json